### ISSUE TITLE
This site can’t be reached.

### ISSUE THREAD

**Issue by fayasnoushad** [urmil89/snakegame#1]
Check if there is a typo in [urmil8989.onilne](https://urmil8989.onilne).

DNS_PROBE_FINISHED_NXDOMAIN

**Comment by urmillive** [comment]
yes I know it it's not working

**Comment by fayasnoushad** [comment]
Then add a new domain

**Comment by urmillive** [comment]
sure I'm working on site where i can live my all projecsts

**Comment by fayasnoushad** [comment]
Use github provided domain

**Comment by fayasnoushad** [comment]
Like :- https://urmil89.github.io/snakegame

**Comment by urmillive** [comment]
Let me try bro

**Comment by fayasnoushad** [comment]
Aa
